config_version = 14

[bar.default]
background_opacity = 0.0
capsule = true
capsule_border = "primary"
capsule_radius = 0
end = [ "tray", "notifications", "clipboard", "network", "bluetooth", "battery", "session" ]
margin_ends = 0
radius = 0
scale = 1.2500000111758709
start = [ "wallpaper", "workspaces", "media", "audio_visualizer" ]

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 124.0
    cy = 1002.5
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = true
        background_color = "surface"
        background_opacity = 0.0
        background_padding = 10
        background_radius = 12
        color = "primary"
        color2 = "secondary"
        display = "graph"
        font_family = ""
        gauge_layout = "horizontal"
        highlight_color = "error"
        interface = ""
        label_min_width = 0
        network_speed_compact = false
        network_speed_unit = "auto"
        shadow = true
        show_label = true
        stat = "cpu_usage"
        stat2 = "cpu_temp"

[dock]
auto_hide = true
background_opacity = 0.0
border = "primary"
border_width = 2.5
enabled = true
radius = 0
reserve_space = false
shadow = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
corner_radius_scale = 0.0
font_family = "ZedMono Nerd Font"

    [shell.launcher]
    app_grid = false
    categories = false
    compact = false
    show_app_actions = false
    show_icons = false

    [shell.screenshot]
    directory = "~/Pictures/Screenshots"

[theme]
builtin = "Gruvbox"
mode = "dark"
source = "builtin"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "gtk3", "kcolorscheme", "qt", "sway" ]

[wallpaper.default]
path = "/home/olma/Pictures/Wallpapers/after_school_stroll_gruvbox.png"

[wallpaper.last]
path = "/home/olma/Pictures/Wallpapers/after_school_stroll_gruvbox.png"

[wallpaper.monitors.eDP-1]
path = "/home/olma/Pictures/Wallpapers/after_school_stroll_gruvbox.png"

[widget.network]
show_label = false