

# Commands that should be applied only for interactive shells.
[[ $- == *i* ]] || return

HISTFILESIZE=100000
HISTSIZE=10000

shopt -s histappend
shopt -s extglob
shopt -s globstar
shopt -s checkjobs

alias -- ..='cd ..'
alias -- ll='eza --icons -l'
alias -- ls='eza --icons'
alias -- wgdown='sudo wg-quick down ~/.config/wg-quick/wg0.conf'
alias -- wgup='sudo wg-quick up ~/.config/wg-quick/wg0.conf'


