[colors.primary]
background = '#1f1f28'
foreground = '#dcd7ba'

[colors.cursor]
text = '#1f1f28'
cursor = '#c8c093'

[colors.vi_mode_cursor]
text = '#1f1f28'
cursor = '#76946a'

[colors.search.matches]
foreground = '#2a2a37'
background = '#7e9cd8'

[colors.search.focused_match]
foreground = '#2a2a37'
background = '#76946a'

[colors.footer_bar]
foreground = '#2a2a37'
background = '#e3e3e8'

[colors.hints.start]
foreground = '#2a2a37'
background = '#c0a36e'

[colors.hints.end]
foreground = '#2a2a37'
background = '#c0a36e'

[colors.selection]
text = '#c8c093'
background = '#2d4f67'


[colors.normal]
black   = '#090618'
red     = '#c34043'
green   = '#76946a'
yellow  = '#c0a36e'
blue    = '#7e9cd8'
magenta = '#957fb8'
cyan    = '#6a9589'
white   = '#c8c093'


[colors.bright]
black   = '#727169'
red     = '#e82424'
green   = '#98bb6c'
yellow  = '#e6c384'
blue    = '#7fb4ca'
magenta = '#938aa9'
cyan    = '#7aa89f'
white   = '#dcd7ba'


[colors.dim]
black   = '#090618'
red     = '#c34043'
green   = '#76946a'
yellow  = '#c0a36e'
blue    = '#7e9cd8'
magenta = '#957fb8'
cyan    = '#6a9589'
white   = '#c8c093'
